-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgXliBaGjetGZ/BJeA
ccSaGjk84mDiCdwwOSzXQVYC7L6gCgYIKoZIzj0DAQehRANCAAS6/Ra95pdVt0ZT
IIti2iKDDxSeIJAXFyUyr9PYvzP5fTZEPt/i60dwTgbDv4Ls+9xXkC4n5+oA8m9J
E4sfuzDr
-----END PRIVATE KEY-----